name: Weather Fetch (Hardcoded API Key)

on:
  push:
    branches:
      - main

jobs:
  fetch-weather:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up API key
        run: |
          echo "WEATHER_API_KEY=mock-api-key" >> $GITHUB_ENV
          echo "The API key being used is: mock-api-key"

      - name: Fetch weather data
        run: |
          echo "Weather API Key: $WEATHER_API_KEY"
          # Your command to fetch weather data goes here


