name: Weather API with GitHub Secrets

on:
  push:
    branches:
      - main  # This will trigger the workflow on pushes to the main branch

jobs:
  fetch-weather:
    runs-on: ubuntu-latest  # The environment where the job will run

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run weather script with GitHub secret
        run: |
          export WEATHER_API_KEY=${{ secrets.MY_API_KEY }}  # Use the secret securely
          curl -s "https://api.openweathermap.org/data/2.5/weather?q=Toronto&appid=$WEATHER_API_KEY"
